# Generated by ai_testgen (openai: gemini-3.8-flash) on 2026-09-23 00:36
# Target: events/views_profile.py | +40 covered lines | 60.06% -> 66.45%
# Reviewed by: Nena (added 2 assertions, corrected docstring)

from datetime import timedelta

import pytest
from django.urls import reverse
from django.utils import timezone

from tests.conftest import EventFactory, OrderFactory, OrderItemFactory, TicketTypeFactory

pytestmark = pytest.mark.django_db


def test_profile_requires_login(client):
    """Anonymous access to profile view redirects to login page."""
    response = client.get(reverse("profile"))

    assert response.status_code == 302
    assert response.url.startswith(reverse("login"))


def test_profile_no_orders_shows_empty_state(client, django_user_model):
    """Authenticated user with no placed orders has has_tickets=False and empty recommendations."""
    user = django_user_model.objects.create_user(username="emptyuser", password="password123")
    # Cart order should be ignored
    cart_order = OrderFactory(user=user, status="cart")
    OrderItemFactory(order=cart_order)

    client.force_login(user)
    response = client.get(reverse("profile"))

    assert response.status_code == 200
    assert response.context["has_tickets"] is False
    assert response.context["recommendations"] == []
    assert response.context["user"] == user


def test_profile_active_and_expired_tickets_with_recommendations(client, django_user_model):
    #checked version
    """Placed orders decide the categories; bought and past events are excluded, top category comes first."""
    # Docstring corrected by reviewer Nena (the original claimed to check active/expired split,
    # which is not visible in the view's context)
    user = django_user_model.objects.create_user(username="musicfan", password="password123")
    now = timezone.now()

    # Active concert order (3 tickets) -> Concert will be top category
    active_concert = EventFactory(
        category="concert",
        datetime=now + timedelta(days=5),
        name="Active Concert",
    )
    order_active = OrderFactory(user=user, status="placed")
    tt_active = TicketTypeFactory(event=active_concert)
    OrderItemFactory(order=order_active, ticket_type=tt_active, qty=3)

    # Expired concert order (1 ticket)
    expired_concert = EventFactory(
        category="concert",
        datetime=now - timedelta(days=10),
        name="Past Concert",
    )
    tt_expired_concert = TicketTypeFactory(event=expired_concert)
    OrderItemFactory(order=order_active, ticket_type=tt_expired_concert, qty=1)

    # Expired theatre order (1 ticket) -> Theatre will be an "other" category
    expired_theatre = EventFactory(
        category="theatre",
        datetime=now - timedelta(days=3),
        name="Past Theatre Show",
    )
    order_past = OrderFactory(user=user, status="placed")
    tt_theatre = TicketTypeFactory(event=expired_theatre)
    OrderItemFactory(order=order_past, ticket_type=tt_theatre, qty=1)

    # Future events available for recommendation
    rec_concert = EventFactory(
        category="concert",
        datetime=now + timedelta(days=2),
        name="Recommended Concert",
    )
    rec_theatre = EventFactory(
        category="theatre",
        datetime=now + timedelta(days=4),
        name="Recommended Theatre",
    )
    # Event in another category with no purchases should not be recommended
    EventFactory(
        category="sport",
        datetime=now + timedelta(days=6),
        name="Sport Event",
    )
    # Past event in concert category should not be recommended
    EventFactory(
        category="concert",
        datetime=now - timedelta(days=1),
        name="Old Concert",
    )

    client.force_login(user)
    response = client.get(reverse("profile"))

    assert response.status_code == 200
    assert response.context["has_tickets"] is True

    recommendations = response.context["recommendations"]
    rec_events = [r["event"] for r in recommendations]

    # Purchased events should not be in recommendations
    assert active_concert not in rec_events
    assert expired_concert not in rec_events
    assert expired_theatre not in rec_events

    # Both recommended events should appear
    assert rec_concert in rec_events
    assert rec_theatre in rec_events

    #THIS PART IS ADDED BY REVIEWER NENA
    # events from categories never bought, and past events, are not recommended
    assert all(r["event"].name not in ("Sport Event", "Old Concert") for r in recommendations)
    # top category recommendations come before the other categories
    assert rec_events.index(rec_concert) < rec_events.index(rec_theatre)

    # Check top category flag and category display
    concert_rec = next(r for r in recommendations if r["event"] == rec_concert)
    assert concert_rec["is_top_category"] is True
    assert concert_rec["category_display"] == "Concert"

    theatre_rec = next(r for r in recommendations if r["event"] == rec_theatre)
    assert theatre_rec["is_top_category"] is False
    assert theatre_rec["category_display"] == "Theatre"


def test_profile_top_categories_tie(client, django_user_model):
    """When multiple categories tie for the highest ticket count, all are treated as top categories."""
    user = django_user_model.objects.create_user(username="tieuser", password="password123")
    now = timezone.now()

    festival_event = EventFactory(category="festival", datetime=now - timedelta(days=2))
    sport_event = EventFactory(category="sport", datetime=now - timedelta(days=1))

    order = OrderFactory(user=user, status="placed")
    OrderItemFactory(
        order=order,
        ticket_type=TicketTypeFactory(event=festival_event),
        qty=2,
    )
    OrderItemFactory(
        order=order,
        ticket_type=TicketTypeFactory(event=sport_event),
        qty=2,
    )

    rec_festival = EventFactory(category="festival", datetime=now + timedelta(days=3))
    rec_sport = EventFactory(category="sport", datetime=now + timedelta(days=4))

    client.force_login(user)
    response = client.get(reverse("profile"))

    assert response.status_code == 200
    recommendations = response.context["recommendations"]
    rec_events = [r["event"] for r in recommendations]

    assert rec_festival in rec_events
    assert rec_sport in rec_events
    for r in recommendations:
        assert r["is_top_category"] is True
